### ISSUE TITLE
ImportX and MODX Revolution 3

### ISSUE THREAD

**Issue by AntonFix** [modmore/importX#73]
Hello,
I can't install and start ImportX on MODX 3.

```
No foreign key definition for parentClass: MODX\Revolution\modMenu using relation alias: Action
No foreign key definition for parentClass: MODX\Revolution\modMenu using relation alias: Action
```

Link to ImportX is wrong: https://***/manager/?a=1

![chrome_B5JCUlXS1i](https://user-images.githubusercontent.com/2990135/195085543-3663ac02-eeed-46c4-8a40-550d154ca767.png)

**Comment by Mark-H** [comment]
Oh, I didn't realise that was still in use in ImportX. Looks like it will need updated controllers and processors as well to work in MODX 3. I'll put it on the list.

**Comment by muzzwood** [comment]
Fixed in https://github.com/modmore/importX/pull/74
Release incoming! 🚀
